application/root/forms.py
from flask_wtf import FlaskForm
from wtforms import RadioField, HiddenField, SubmitField
from wtforms.validators import DataRequired


class ParticipantForm(FlaskForm):
    participant = RadioField('Participant', choices=[(d, 'Participant %d' % d) for d in range(1, 21)], validators=[DataRequired()])
    start = SubmitField(label='start')


class TaskListForm(FlaskForm):
    yes = SubmitField(label='yes')
    no = SubmitField(label='no')

    participant = HiddenField('participant')
    task_1_complete = HiddenField('task_1_complete')
    task_2_complete = HiddenField('task_2_complete')
    task_3_complete = HiddenField('task_3_complete')
    task_4_complete = HiddenField('task_4_complete')

    choices = [('task_1', 'Icon Menu'), ('task_2', 'Swipe Menu'),
               ('task_3', 'Original Menu'), ('task_4', 'Alternate Device')]
    task = RadioField('Task', choices=choices)


class TaskForm(FlaskForm):
    participant = HiddenField('participant')
    task_1_complete = HiddenField('task_1_complete')
    task_2_complete = HiddenField('task_2_complete')
    task_3_complete = HiddenField('task_3_complete')
    task_4_complete = HiddenField('task_4_complete')


class EndTaskForm(FlaskForm):
    yes = SubmitField(label='yes')
    no = SubmitField(label='no')

    participant = HiddenField('participant')
    task_1_complete = HiddenField('task_1_complete')
    task_2_complete = HiddenField('task_2_complete')
    task_3_complete = HiddenField('task_3_complete')
    task_4_complete = HiddenField('task_4_complete')

application/root/__init__.py
from flask import Blueprint

root_blueprint = Blueprint('root', __name__)

from application.root.views import index

application/root/views.py
from datetime import datetime

from flask import render_template, request, url_for, redirect
from application.services.google_service import google_service

from application.config import Config
from application.root import root_blueprint
from application.root.forms import ParticipantForm, TaskListForm, TaskForm, EndTaskForm


@root_blueprint.route('/record-event')
def record_event():
    if request.method == 'GET':
        try:
            participant = request.values['participant']
            task = request.values['amp;task']
            action = request.values['amp;action']
            value = request.values['amp;value']
        except:
            participant = 'error'
            task = ''
            action = ''
            value = ''

        write_to_google(participant, task, action, value)

    return 'recorded'

def write_to_google(participant, task, action, value):

    now = datetime.now()
    date_str = now.strftime('%d-%m-%Y')
    time_str = now.strftime('%H:%M:%S')
    seconds_since_midnight = (now - now.replace(hour=0, minute=0, second=0, microsecond=0)).total_seconds()
    cells = [date_str, time_str, participant, task, action, value, seconds_since_midnight]

    google_service.add_row(cells)


@root_blueprint.route('/', methods=['GET', 'POST'])
def index():
    if request.method == 'GET':
        form = ParticipantForm()
        return render_template('index.html', form=form)
    else:
        form = ParticipantForm(request.form)
        if form.data['participant'] == 'None':
            return redirect(url_for('root.index'))

        return redirect(url_for('root.tasks',
                                participant=form.data['participant'],
                                task_1_complete=False, task_2_complete=False, task_3_complete=False,
                                task_4_complete=False))


@root_blueprint.route('/tasks', methods=['GET', 'POST'])
def tasks():
    if request.method == 'GET':
        form = TaskListForm(request.values)

        return render_template('tasks.html', form=form,
                               task_order=order_for_participant(request.values['participant']))
    else:
        form = TaskListForm(request.form)
        if form.data['yes']:
            if form.data['task'] == 'task_1':
                return redirect(url_for('root.icon_menu',
                                        participant=form.data['participant'],
                                        task_1_complete=form.data['task_1_complete'],
                                        task_2_complete=form.data['task_2_complete'],
                                        task_3_complete=form.data['task_3_complete'],
                                        task_4_complete=form.data['task_4_complete']))
            elif form.data['task'] == 'task_2':
                return redirect(url_for('root.swipe_cards',
                                        participant=form.data['participant'],
                                        task_1_complete=form.data['task_1_complete'],
                                        task_2_complete=form.data['task_2_complete'],
                                        task_3_complete=form.data['task_3_complete'],
                                        task_4_complete=form.data['task_4_complete']))
            elif form.data['task'] == 'task_3':
                return redirect(url_for('root.sub_menus',
                                        participant=form.data['participant'],
                                        task_1_complete=form.data['task_1_complete'],
                                        task_2_complete=form.data['task_2_complete'],
                                        task_3_complete=form.data['task_3_complete'],
                                        task_4_complete=form.data['task_4_complete']))
            elif form.data['task'] == 'task_4':
                return redirect(url_for('root.external',
                                        participant=form.data['participant'],
                                        task_1_complete=form.data['task_1_complete'],
                                        task_2_complete=form.data['task_2_complete'],
                                        task_3_complete=form.data['task_3_complete'],
                                        task_4_complete=form.data['task_4_complete']))
            else:
                return redirect(url_for('root.index'))
        else:
            return redirect(url_for('root.index'))


def order_for_participant(participant):
    return [(int(participant) + i - 1) % 4 for i in range(0, 4)]


@root_blueprint.route('/icon-menu', methods=['GET', 'POST'])
def icon_menu():

    if request.method == 'GET':
        form = TaskForm(request.values)
        return render_template('tasks/icon_menu.html', form=form, rows=5, cols=3, icons=Config.CHOICES)
    else:
        form = EndTaskForm(request.values)

        task_1_complete = True if form.data['yes'] else form.data['task_1_complete']
        return redirect(url_for('root.tasks',
                                participant=form.data['participant'],
                                task_1_complete=task_1_complete,
                                task_2_complete=form.data['task_2_complete'],
                                task_3_complete=form.data['task_3_complete'],
                                task_4_complete=form.data['task_4_complete']))


@root_blueprint.route('/swipe-cards', methods=['GET', 'POST'])
def swipe_cards():

    if request.method == 'GET':
        form = TaskForm(request.values)
        return render_template('tasks/swipe_cards.html', form=form, cards=Config.CHOICES)
    else:
        form = EndTaskForm(request.values)

        task_2_complete = True if form.data['yes'] else form.data['task_2_complete']
        return redirect(url_for('root.tasks',
                                participant=form.data['participant'],
                                task_1_complete=form.data['task_1_complete'],
                                task_2_complete=task_2_complete,
                                task_3_complete=form.data['task_3_complete'],
                                task_4_complete=form.data['task_4_complete']))


@root_blueprint.route('/sub-menus', methods=['GET', 'POST'])
def sub_menus():
    if request.method == 'GET':
        form = TaskForm(request.values)
        return render_template('tasks/sub_menu.html', form=form, tree=Config.TREE)
    else:
        form = EndTaskForm(request.values)

        task_3_complete = True if form.data['yes'] else form.data['task_3_complete']
        return redirect(url_for('root.tasks',
                                participant=form.data['participant'],
                                task_1_complete=form.data['task_1_complete'],
                                task_2_complete=form.data['task_2_complete'],
                                task_3_complete=task_3_complete,
                                task_4_complete=form.data['task_4_complete']))


@root_blueprint.route('/external', methods=['GET', 'POST'])
def external():

    if request.method == 'GET':
        form = TaskForm(request.values)
        return render_template('tasks/external.html', form=form)
    else:
        form = EndTaskForm(request.values)

        task_4_complete = True if form.data['yes'] else form.data['task_4_complete']
        return redirect(url_for('root.tasks',
                            participant=form.data['participant'],
                            task_1_complete=form.data['task_1_complete'],
                            task_2_complete=form.data['task_2_complete'],
                            task_3_complete=form.data['task_3_complete'],
                            task_4_complete=task_4_complete))

application/templates/tasks/external.html
{% from "tasks/forms.html" import render_yes_no_footer %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700,900" rel="stylesheet">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/solid.css"
          integrity="sha384-TbilV5Lbhlwdyc4RuIV/JhD8NR+BfMrvz4BL5QFa2we1hQu6wvREr3v6XSRfCTRp" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/fontawesome.css"
          integrity="sha384-ozJwkrqb90Oa3ZNb+yKFW2lToAWYdTiF1vt8JiH5ptTGHTGcN7qdoR1F95e0kYyG" crossorigin="anonymous">

    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">

    <link rel="shortcut icon" type="image/png" href="img/favicon.png">

    <title>Litter bug</title>
</head>
<body>
<header>
    <div class="header-bar heading-tertiary">
        Litter bug
    </div>
</header>
<main>
    <div id="section-start" class="section-litter-bug">
        <div class="container">
            <div class="row">
                <div class="col">
                    <div class="heading-secondary">
                        Task 4
                    </div>
                    <div class="heading-tertiary">
                        External task
                    </div>
                    <div class="paragraph">
                        This is a the start page for the external task
                    </div>
                    <div class="paragraph">
                        This task is completed outside this app
                    </div>
                    <div class="paragraph">
                        Tap <strong>Exit</strong> to return to the task list
                    </div>
                </div>
            </div>
        </div>

        <div class="yes-no">
            <div class="footer-bar" id="sticky-footer">
                <div class="container">
                    <div class="row">
                        <div class="col">
                            <div id="start-yes-button" class="yes-no__button yes-no__button--yes"
                                 onclick="clickStart()">
                                <span class="fas fa-check"></span>
                            </div>
                        </div>
                        <div class="col">
                            <div id="start-no-button" class="yes-no__button yes-no__button--no" onclick="clickBack()">
                                <span class="fas fa-times"></span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="section-finalise" class="section-litter-bug" style="display: none">
        <form id="external-form" action="{{ url_for('root.external') }}" method='post' class="icon-task__form">
            {{ form.participant }}
            {{ form.task_1_complete }}
            {{ form.task_2_complete }}
            {{ form.task_3_complete }}
            {{ form.task_4_complete }}
            {{ form.csrf_token }}
            {{ render_yes_no_footer() }}
        </form>
    </div>

</main>
</body>
</html>
<script
        src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
        crossorigin="anonymous"></script>

<script type="text/javascript" src="//code.jquery.com/jquery-1.11.0.min.js"></script>
<script type="text/javascript" src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
<script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>


<script>
    var participant = getUrlParameter('participant');
    task = 'external';


    function clickBack() {
        document.getElementById('external-form').submit();
    }

    function deactivateNextButton() {
        document.getElementById('start-yes-button').classList.add('yes-no__button--yes-disabled')
    }

    document.addEventListener("DOMContentLoaded", function (event) {
        deactivateNextButton();
        postEventToGoogle(participant, task, 'Began task External', '')
    });

    function postEventToGoogle(participant, task, action, value) {
        console.log(participant, task, action, value);

        var url = "{{ url_for('root.record_event', participant='PARTICIPANT_PLACEHOLDER', task='TASK_PLACEHOLDER', action='ACTION_PLACEHOLDER', value='VALUE_PLACEHOLDER') }}";
        url = url.replace('PARTICIPANT_PLACEHOLDER', participant);
        url = url.replace('TASK_PLACEHOLDER', task);
        url = url.replace('ACTION_PLACEHOLDER', action);
        url = url.replace('VALUE_PLACEHOLDER', value);

        $.ajax({
            type: "GET",
            url: url,
            success: function () {
                console.log('logged to googledoc')
            }
        });
    }

    function getUrlParameter(sParam) {
        var sPageURL = decodeURIComponent(window.location.search.substring(1)),
            sURLVariables = sPageURL.split('&'),
            sParameterName,
            i;

        for (i = 0; i < sURLVariables.length; i++) {
            sParameterName = sURLVariables[i].split('=');

            if (sParameterName[0] === sParam) {
                return sParameterName[1] === undefined ? true : sParameterName[1];
            }
        }
    };


</script>

application/templates/tasks/forms.html
{% macro render_icon_list(icons, rows, cols) -%}
    <fieldset class="animal-button__fieldset">
        <div class="container">
            {% for row in range(rows) %}
                <div class="row">
                    {% for col in range(cols) %}
                        <div class="col-1-of-4">

                            {% set choice = icons.choices[col + 4*row] -%}
                            {% set image_url = url_for('static', filename="images/icons/" + choice['image']) -%}

                            <div class="animal-button" id="{{ choice[0] }}" onclick="clickAnimalButton('{{ choice[0] }}')">
                                <label for="icons-{{ col + 4*row - 1 }}"><img src="{{ image_url }}" class="animal-button__image"></label>
                                <input id="icons-{{ col + 4*row - 1 }}" class="animal-button__radio-button" name="icons" type="radio" value="{{ choice[0] }}">

                            </div>
                        </div>
                    {% endfor %}
                </div>
            {% endfor %}
        </div>
    </fieldset>
{%- endmacro %}

{%  macro render_swipe_icons(icons) -%}
    <div class="swipe-icons">
        {% for icon in icons.choices %}
            {% set image_url = url_for('static', filename="images/animals/" + icon[0].lower() + ".png") -%}
            <div class="swipe-icon">
            <div class="animal-swipe-choice">
                <div class="animal-swipe-icon">
                        <label for="icons-{{ loop.index }}"><img src="{{ image_url }}" class="animal-swipe-choice__image"></label>
                        <input id="icons-{{ loop.index }}" class="animal-button__radio-button" name="icons" type="radio" value="{{ icon[0] }}" />
                </div>
            </div>
            </div>
        {%  endfor %}
    </div>
{%- endmacro %}


{% macro render_yes_no_footer() -%}
<div class="yes-no">
<div class="footer-bar" id="sticky-footer">
    <div class="row">
        <div class="col-1-of-2">
            <button id="yes" name="yes" type="submit" value="yes" class="footer-bar__confirm buzz-btn buzz-btn-confirm buzz-btn-confirm-disabled yes-no__button yes-no-button--yes">Yes</button>
        </div>
        <div class="col-1-of-2">
            <button id="no" name="no" type="submit" value="no"  class="footer-bar__give-up buzz-btn buzz-btn-warning yes-no__button yes-no__button--no">No</button>
        </div>
    </div>
</div>
</div>
{%- endmacro %}

application/templates/tasks/icon_menu.html
{% from "tasks/forms.html" import render_yes_no_footer %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/solid.css"
          integrity="sha384-TbilV5Lbhlwdyc4RuIV/JhD8NR+BfMrvz4BL5QFa2we1hQu6wvREr3v6XSRfCTRp" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/fontawesome.css"
          integrity="sha384-ozJwkrqb90Oa3ZNb+yKFW2lToAWYdTiF1vt8JiH5ptTGHTGcN7qdoR1F95e0kYyG" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700,900" rel="stylesheet">

    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">

    <link rel="shortcut icon" type="image/png" href="img/favicon.png">

    <title>Litter bug</title>
</head>
<body>
<header>
    <div class="header-bar heading-tertiary">
        Litter bug
    </div>
</header>
<main>
    <div id="section-start" class="section-litter-bug">
        <div class="container">
            <div class="row">
                <div class="col">
                    <div class="heading-secondary">
                        Task 1
                    </div>
                    <div class="heading-tertiary">
                        Icon menu
                    </div>
                    <div class="paragraph">
                        This is a the start page for the one icon menu
                    </div>
                    <div class="paragraph">
                        A task cycles through three pages - start, pick and confirm until you click exit on the start
                        page
                    </div>
                    <div class="paragraph">
                        Tap <strong>Next</strong> to classify more litter
                    </div>
                    <div class="paragraph">
                        Tap <strong>Exit</strong> to return to the task list
                    </div>
                </div>
            </div>
        </div>

        <div class="yes-no">
            <div class="footer-bar" id="sticky-footer">
                <div class="container">
                    <div class="row">
                        <div class="col">
                            <div id="start-yes-button" class="yes-no__button yes-no__button--yes"
                                 onclick="clickStart()">
                                <span class="fas fa-check"></span>
                            </div>
                        </div>
                        <div class="col">
                            <div id="start-no-button" class="yes-no__button yes-no__button--no" onclick="clickBack()">
                                <span class="fas fa-times"></span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="section-play" class="section-litter-bug" style="display: none;">
        <div class="container">
            <fieldset>
                <div class="section-litter-bug__task-menu">
                    {% for row in range(rows) %}
                        <div class="row">
                            {% for col in range(cols) %}
                                <div class="col icon-col">
                                    {% set icon = icons[col + cols*row] -%}
                                    {% set image_url = url_for('static', filename="images/icons/" + icon['image']) -%}

                                    <div class="icon" id="{{ icon['item'] }}"
                                         onclick="clickIcon('{{ icon['item'] }}')">
                                        <img src="{{ image_url }}" class="icon__image">
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    {% endfor %}
                    <div class="row">
                        <div class="col">
                            &nbsp;
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            &nbsp;
                        </div>
                    </div>
                </div>
            </fieldset>
        </div>

        <div class="yes-no">
            <div class="footer-bar" id="sticky-footer">
                <div class="container">
                    <div class="row">
                        <div class="col">
                            <div id="task-yes-button" class="yes-no__button yes-no__button--yes"
                                 onclick="clickIconYes()">
                                <span class="fas fa-check"></span>
                            </div>
                        </div>
                        <div class="col">
                            <div id="task-no-button" class="yes-no__button yes-no__button--no" onclick="clickIconNo()">
                                <span class="fas fa-times"></span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="section-confirm" class="section-litter-bug" style="display: none">
        <div class="container">
            <div class="row">
                <div class="col">
                    <div class="heading-secondary">
                        Task 1
                    </div>
                    <div class="heading-tertiary">
                        Icon menu
                    </div>
                    <div class="paragraph">
                        This screen is to confirm the choice
                    </div>
                    <img class="whole-screen-image" id="confirm-image"/>
                </div>
            </div>
        </div>

        <div class="yes-no">
            <div class="footer-bar" id="sticky-footer">
                <div class="container">
                    <div class="row">
                        <div class="col">
                            <div class="yes-no__button yes-no__button--yes" onclick="clickConfirmYes()">
                                <span class="fas fa-check"></span>
                            </div>
                        </div>
                        <div class="col">
                            <div class="yes-no__button yes-no__button--no" onclick="clickConfirmNo()">
                                <span class="fas fa-times"></span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="section-finalise" class="section-litter-bug" style="display: none">
        <form id="icon-menu-form" action="{{ url_for('root.icon_menu') }}" method='post' class="icon-task__form">
            {{ form.participant }}
            {{ form.task_1_complete }}
            {{ form.task_2_complete }}
            {{ form.task_3_complete }}
            {{ form.task_4_complete }}
            {{ form.csrf_token }}
            {{ render_yes_no_footer() }}
        </form>
    </div>

</main>
</body>
</html>

<script
        src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
        crossorigin="anonymous"></script>
<script>
    var participant = getUrlParameter('participant');
    var task = 'Icon menu';
    postEventToGoogle(participant, task, 'Began task Icon menu', '');

    var selected_icon = "";
    var icons = {{ icons|safe}};
    var root_url = '{{ url_for('static', filename="images/icons") }}'

    function clickIcon(icon) {
        selected_icon = icon;
        deselectAllIcons();
        selectIcon(selected_icon);
        activateTaskYesButton();

        sendClickToServer(icon);
    };

    function clickStart() {
        postEventToGoogle(participant, task, 'start', '');
        $('#section-start').hide();
        $('#section-play').show();
    }

    function clickBack() {
        document.getElementById('icon-menu-form').submit();
    }

    function clickIconYes() {
        updateConfirmSection();
        $('#section-play').hide();
        $('#section-confirm').show();
    }

    function clickIconNo() {
        deselectAllIcons();
        selected_icon = "";
        deactivateTaskYesButton();

        $('#section-start').show();
        $('#section-play').hide();
    }

    function updateConfirmSection() {
        for (var i in icons) {
            if (icons[i]['item'] === selected_icon) {
                var image_url = root_url + '/' + icons[i]['image'];
                $('#confirm-image').attr("src", image_url);
            }
        }
    }

    function clickConfirmYes() {
        postEventToGoogle(participant, task, 'confirm', selected_icon);

        deselectAllIcons();
        selected_icon = "";
        deactivateTaskYesButton();

        $('#section-confirm').hide();
        $('#section-start').show();
    }

    function clickConfirmNo() {
        $('#section-confirm').hide();
        $('#section-play').show();
    }

    function deselectAllIcons() {
        var icons = document.getElementsByClassName("icon");
        for (var i in icons) {
            var icon = icons[i];
            if (icon && icon.classList) {
                icon.classList.remove("icon-selected");
            }
        }
    }

    function selectIcon(icon) {
        document.getElementById(icon).classList.add("icon-selected");
    }

    function activateTaskYesButton() {
        document.getElementById('task-yes-button').classList.remove('yes-no__button--yes-disabled')
    }

    function deactivateTaskYesButton() {
        document.getElementById('task-yes-button').classList.add('yes-no__button--yes-disabled')
    }

    document.addEventListener("DOMContentLoaded", function (event) {
        deactivateTaskYesButton();
    });


    function postEventToGoogle(participant, task, action, value) {
        console.log(participant, task, action, value);

        var url = "{{ url_for('root.record_event', participant='PARTICIPANT_PLACEHOLDER', task='TASK_PLACEHOLDER', action='ACTION_PLACEHOLDER', value='VALUE_PLACEHOLDER') }}";
        url = url.replace('PARTICIPANT_PLACEHOLDER', participant);
        url = url.replace('TASK_PLACEHOLDER', task);
        url = url.replace('ACTION_PLACEHOLDER', action);
        url = url.replace('VALUE_PLACEHOLDER', value);

        $.ajax({
            type: "GET",
            url: url,
            success: function () {
                console.log('logged to googledoc')
            }
        });
    }

    function getUrlParameter(sParam) {
        var sPageURL = decodeURIComponent(window.location.search.substring(1)),
            sURLVariables = sPageURL.split('&'),
            sParameterName,
            i;

        for (i = 0; i < sURLVariables.length; i++) {
            sParameterName = sURLVariables[i].split('=');

            if (sParameterName[0] === sParam) {
                return sParameterName[1] === undefined ? true : sParameterName[1];
            }
        }
    };


</script>